### ISSUE TITLE
an addition to options.h

### ISSUE THREAD

**Issue by NathanTech7713** [lisdude/toaststunt#10]
Could we have an addition to options.h to say whether to use the last_move prop or not? It's useful on smaller databases, but can really blote bigger ones, :) It's a great feature though. Would be even better if we could have it in $server_options.enable_last_move, but I'm thinking that could get complicated.

**Comment by distantorigin** [comment]
I added a startup flag ('-m') in a8218d9dc5f05c3bde1b86ac536260ab66580dc9 to clear all existing last_move properties, and never set them for the duration of the server's lifetime.
