### ISSUE TITLE
crash with garbage

### ISSUE THREAD

**Issue by NathanTech7713** [lisdude/toaststunt#13]
Hi there,
if a player is in a garbage object, it appears to cause a memory error (signall 11), after around 5 to 10 seconds of the player trying to do stuff.
HTH, though calling move(obj, new_location) fixes it and doesn't break, it is still something I noticed.
HTH

**Comment by lisdude** [comment]
Hmmm. How are you getting a player in an invalid object? Recycle() should move everything and move() shouldn't allow anything into an invalid... Can you give me steps to reproduce this?

**Comment by NathanTech7713** [comment]
Hi Lissdude,
Sorry for the unintentional obscurity. By garbage, I mean a child of garbage object, usually #64 or $garbage.
To reproduce:
1. Chooes a player of choice, this happened to be a builder of mine.
2. player_obj:moveto(a child of #64)
3. Get the player to type a few commands.
Ordinarily you'd get a couple tracebacks, and not much else. what seems to happen though is a couple tracebacks, then a crash.
HTH

**Comment by distantorigin** [comment]
It's not really feasible to debug this without having MOOcode for the
verbs players are trying to execute. After several failed attempts on
multiple MOOs, I can't reproduce this.
