### ISSUE TITLE
What would cause this?

### ISSUE THREAD

**Issue by NathanTech7713** [lisdude/toaststunt#15]
hi there,
So I was running a server the other day, when I noticed this pop up:
*** Waiting for network I/O: Bad file descriptor               

During this time, nothing could connect to h the mud, though I'm assuming it carried on running as normal.
left it over night, and got up the next morning, it was working fine.
Huge log file, mind you.
thanks for any help

**Comment by distantorigin** [comment]
I advise investigating `ulimit`, `sysctl`, or other security mechanisms built into your operating system. This is not a ToastStunt specific issue and/or bug; your system merely brushed up against the descriptor limit and you should adjust it or figure out what user or other process is consuming them.

**Comment by immibis** [comment]
I would like to point out that "Bad file descriptor" from `select` can only be the result of a bug in the program. Perhaps the bug is triggered by running out of file descriptors, but `select` does not return "Bad file descriptor" merely because the process is out of file descriptors.
