### ISSUE TITLE
Db changes

### ISSUE THREAD

**Issue by NathanTech7713** [lisdude/toaststunt#19]
Hi there,
I was wondering what changes does toast stunt actually make to the database as compared to the normal stunt?
thanks

**Comment by tvdijen** [comment]
Compare https://github.com/lisdude/toaststunt/blob/master/src/include/version.h#L42-L86 to the original Stunt-version and you should get an idea of the changes..

**Comment by NathanTech7713** [comment]
Thanks Tim, that's very interesting.
Would you know where to look, as well, roughly to see how this is written in the writing of the database?
I took a look at write_db_file and it looks similar to the stunt code. Obviously, though, even if you remove the section about waifs, and change the db version number, stunt will not load a databaes previously in stunt.
I admit I'm not using an import core to test this sort of thing out, but I am interested enough to see if, considering how close they are, how hard it would be to load a database into toaststunt, dump it out into stunt format, then load it back onto stunt?
Reading the link you provided in comparison it seems that waifs and threaded info are the two biggest structure changes, while I can't  see why the builtin prop would be a problem.
Thanks for any tips

**Comment by tvdijen** [comment]
Any DB change should reflect into an entry into this file, which will automatically update the DB-version number.. Looking at this project in general, I wouldn't be surprised if they didn't do this at some point..
I guess your best chance is to go over the changelog and/or post details about the `I can't see why the builtin prop would be a problem` so we can try and help you
