### ISSUE TITLE
Ansi advice for welcome screen?

### ISSUE THREAD

**Issue by anubi** [lisdude/toaststunt#26]
Hi, this isn't an issue I just am not sure where to turn. The ansi system doesn't replace tags for $login:welcome (presumably because a not-logged-in-player doesn't have ansi options enabled) and digging through the $ansi code, I'm not sure how to make it happen. I've tried a myriad of hacks to try to get it to work, but I keep seeing my ansi tags in my welcome message. Is this really tricky to pull off? If someone could point me in the direction of where to start reading, it'd be super appreciated.

**Comment by distantorigin** [comment]
A quick way is using the `parse_ansi()` builtin in conjunction with `notify()` in $login:welcome.

```notify(connection, parse_ansi(STR text));```

Be aware that this will not parse xterm-256 or 24-bit colors; you are limited to the standard colors available in 4-bit ANSI. If you're using ToastCore, explore updating $ansi_utils:notify to support non-player connections.

**Comment by anubi** [comment]
Thanks!
