### ISSUE TITLE
Large memory leak

### ISSUE THREAD

**Issue by NathanTech7713** [lisdude/toaststunt#32]
Hi Folks,
This is just to raise awareness that there seems to be a large memory leak with the latest versin of the server.
there also seems to be some database changes between 16 and 17 (well obviously) but I'm not sure at which change these came in?
The memory leak is extremely serious and I'm assuming it's related to networking.
Interestingly, when ever I compile with LeakCheck or Debug it actually won't boot, it loads the database, listens, and then crashes.
I'm assuming this was introduced at the latest network changes?
Wondering if someone can advise a way to role bak temporarily or if 17 came with the network changes.
thanks

**Comment by distantorigin** [comment]
Database version 17 was introduced in May of this year for the boolean [BOOL] type in 4aba152. You can see a list of all database versions in version.h, specifically [here](https://github.com/lisdude/toaststunt/blob/master/src/include/version.h#L36).

If you can, please try rolling back to a previous commit and identifying at which commit it decides to not load. Any versions of master after the aforementioned commit have the database changes. (If you already have a "last known good commit" that would be helpful, too.)

**Comment by NathanTech7713** [comment]
Hi there,
 I just managed to get it to load on 5e9c5d3
https://github.com/lisdude/toaststunt/commit/5e9c5d3975af9280a0ae641bc4dacc6846b79c1d

As you'd probably expect I suppose.
Having run more tests as well, the memory goes up at an almost constant rate when there are players around, doing things, but on a server where it's just doing standard coded things like you know, scheduler tasks, making npc's move about and running enemies an such it doesn't leak.
There was a slight jump of 188k bytes but that's pretty normal one assumes for tasks and such?
I'm wondering if a free got missed in the network.cc merges?
I'll run some memory checks on 5e9c5d3 and report back.

**Comment by NathanTech7713** [comment]
Update, while preparing to role back, I noticed in one of the patches I applied to the latest version I had misplaced a free_stream which should have freed new_stream(25). I suspect this would be the cause of the issue. Sorry for the scare.
