### ISSUE TITLE
failing at make stage 

### ISSUE THREAD

**Issue by FelixNettle** [lisdude/toaststunt#33]
Trying to install on a fresh ubuntu.
After cmake, the make command stops at 62%with:
/home/MOO/toaststunt/src/network.cc:389:5: error: expected unqualified-id before ‘if’
  389 |     if (count > 0) {
      |     ^~
/home/MOO/toaststunt/src/network.cc:440:7: error: expected unqualified-id before ‘else’
  440 |     } else {
      |       ^~~~
/home/MOO/toaststunt/src/network.cc:444:1: error: expected declaration before ‘}’ token
  444 | }
      | ^
make[2]: *** [CMakeFiles/moo.dir/build.make:653: CMakeFiles/moo.dir/src/network.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/moo.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by lisdude** [comment]
Sorry about that. Commenting out USE_TLS should actually work now.
