### ISSUE TITLE
toobj()

### ISSUE THREAD

**Issue by Dino804** [lisdude/toaststunt#39]
I just experienced a bug in the built-in function toobj()
For instance, if you evaluate ;toobj("root") (or whatever string), it returns the system object #0, but it should be returned #-1 <$nothing> instead.

**Comment by tvdijen** [comment]
This has been like this since dinosaurs were on this planet...  Changing this would cause a lot of backwards-compatible issues.
See Lambdamoo original builtin reference;  https://tecfa.unige.ch/guides/MOO/ProgMan/ProgrammersManual_42.html#SEC42

**Comment by distantorigin** [comment]
@tvdijen is correct. This is defined functionality, not a bug. See below:

```
Function: obj toobj (value)
Converts the given MOO value into an object number and returns that object number. The conversions are very similar to those for toint() except that for strings, the number may be preceded by ‘#’.

toobj("34")       ⇒   #34
toobj("#34")      ⇒   #34
toobj("foo")      ⇒   #0
toobj({1, 2})     error-->   E_TYPE
```

**Comment by lisdude** [comment]
If you want to work around it, though, you can always do something like:

@verb #0:bf_toobj tnt
@prog #0:bf_toobj
if (typeof(args[1]) == STR && `args[1][1] ! E_RANGE' != "#" && !$string_utils:is_numeric(args[1]))
  return $nothing;
else
  return toobj(@args);
endif
.
@prop $server_options.protect_toobj 1
;load_server_options()

**Comment by Dino804** [comment]
Many thanks for the workaround. :)
