### ISSUE TITLE
Curl Functionality

### ISSUE THREAD

**Issue by dwog** [lisdude/toaststunt#43]
The current functionality of *curl* is considerably limited and presently generates only HTTP get requests. Unfortunately, this method alone is not enough to allow for effective communication with REST APIs. As such, there is a need for increased HTTP functionality in the form of:
- Post -- Use to request that the server accept data.
- Put -- Use to (more explicitly) request  that the server accept data. The difference primarily derives from the assumptions the server is allowed to make.
- Delete -- Use to request that a server delete the specified entity.
- Trace -- Use to request that the server send back received data. Useful for testing and diagnostic.

  The behavior for these HTTP methods are well-documented here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
As a final thought; The bare-minimum implementation of both get and post would allow for any MOO-driven API to grow vastly in complexity.

**Comment by distantorigin** [comment]
Merging these into a single builtin would be more ideal for reduction of complexity, maintenance, and the currently imposed function table limit. There are other options that we may want from curl in the future outside of HTTP methods as well; as such, I propose converting the second argument in the `curl()` builtin to an option map instead, where these changes to the behavior can be defined. `include_headers` can be folded into this second argument.

**Comment by tvdijen** [comment]
I was thinking the exact same thing as what @distantorigin has written.  Single function with an options-map that resembles curl-parameters

**Comment by dwog** [comment]
Thank you for the feedback. While merging the functions is not impossible -- in fact, that indeed was the original idea -- for the very valid concern that it could and will present an issue with Toaststunt's current limitations, I would argue that doing so would actually reduce complexity and maintenance.
    Such a function possessing numerous responsibilities would inherently become unwieldy, especially when you consider adding yet more behavior. Generally accepted design patterns encourage short -- focused functions in place of lengthy ones. Which is not to say there should never be exceptions, but rather to explain the thought-process behind it.
    I do agree that space should be left in the implementation for eventually specifying protocol(HTTP, FTP, GOFER, IMAP... etc) and welcome more discussion on how we could make that a reality. Adding additional arguments? With all that above stated, I am open  to discuss and adjust accordingly.
If you were curious where I drew my design concepts from: https://google.github.io/styleguide/cppguide.html
