### ISSUE TITLE
:user_disconnected not being called with correct connection object on server restart

### ISSUE THREAD

**Issue by jasonhsw** [lisdude/toaststunt#71]
I have some code that connects to other servers, and connects to an object, rather than calling read().
I noticed that the object wasn't being properly cleaned up when the server restarted, so I put in some debugging code in the verb.
I found that it was getting extremely low object numbers (E.G. #-8771237084393373721), instead of the correct one (#-25 in this case).

**Comment by lisdude** [comment]
Fixed by #80
