### ISSUE TITLE
compiling on ubuntu 22.04.4 results in an error

### ISSUE THREAD

**Issue by danielw97** [lisdude/toaststunt#89]
I'm attempting to compile Toaststunt on ubuntu 22.04.4 with gcc 11.4.0 following the instructions in the readme, however am receiving an error related to curl:
 In file included from /home/daniel/toaststunt/src/curl.cc:5:                    
 /home/daniel/toaststunt/src/curl.cc: In function ‘void curl_thread_callback(Var,
  Var*, void*)’:                                                                 
 /home/daniel/toaststunt/src/curl.cc:58:35: error: ‘CURLOPT_PROTOCOLS_STR’ was no
 t declared in this scope; did you mean ‘CURLOPT_PROTOCOLS’?                     
    58 |     curl_easy_setopt(curl_handle, CURLOPT_PROTOCOLS_STR, "http,https"); 
       |                                   ^~~~~~~~~~~~~~~~~~~~~                 
 make[2]: *** [CMakeFiles/moo.dir/build.make:1102: CMakeFiles/moo.dir/src/curl.cc
 .o] Error 1                                                                     
 make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/moo.dir/all] Error 2          
 make: *** [Makefile:91: all] Error 2                                            
I'm not sure if anyone has encountered this and has a solution?
 Thanks in advance.
Edit:
I've just tried building on debian 12, and don't receive an error on that platform so it may be due to the older gcc version in use on ubuntu?

**Comment by tvdijen** [comment]
More likely it's related to the version of `curl` that is available on Ubuntu..

**Comment by danielw97** [comment]
That's certainly more likely.
I'm personally completely fine running this on debian, so will close this issue.
